name: Continuous Deployment

### This needs the following env variables defined in GitHub secrets ###
#
## AZURE_CREDENTIALS ##
# RESOURCE_ID=$(az group show --name "rg-nubesgen-001" --query id -o tsv)
# SPNAME="sp-$(az webapp list --resource-group rg-nubesgen-001  --query '[].name' -o tsv)"
# az ad sp create-for-rbac --name "${SPNAME}" --role contributor --scopes "$RESOURCE_ID" --sdk-auth
# -> copy this JSON data to the AZURE_CREDENTIALS GitHub secret
#
## APPLICATION_NAME ##
# The application name, as used in App Service.
# In Terraform, this is the "name" of the "azurerm_app_service" resource.

on:
  push:
    branches:
      - staging
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with Maven
        run: mvn package
      - name: Temporarily save package
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: '${{ github.workspace }}/target/*.jar'
          retention-days: 1
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: package
      - name: Login to Azure Spring Cloud
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: 'Deploy to Azure WebApp'
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.APPLICATION_NAME }}
          package: '*.jar'
